name: Dependency Check

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deptry
        run: pip install --no-cache-dir deptry

      - name: Install package
        run: pip install .

      - name: Run dependency check
        run: deptry cvxpy --per-rule-ignores "DEP003=cvxpy"